### ISSUE TITLE
Object binding / configuration interfaces

### ISSUE THREAD

**Issue by swltr** [gestalt-config/gestalt#111]
Since cfg4j seems to be dead, we are looking for a replacement over at https://github.com/opentcs. One feature of cfg4j we're making use of is object binding / configuration interfaces (see https://www.cfg4j.org/releases/latest/#accessing-configuration). Among other things, it helps us ensure all configuration entries we use are documented both for developers as well as users (see [VirtualVehicleConfiguration.java](https://github.com/openTCS/opentcs/blob/55f78678b8cfb1004a9dd37d64cd101579316ae6/openTCS-CommAdapter-Loopback/src/main/java/org/opentcs/virtualvehicle/VirtualVehicleConfiguration.java), for instance).

Unless I have missed it in the documentation, gestalt does not provide object binding. Is it planned to add that as a feature?

**Comment by credmond-git** [comment]
Hello @swltr thanks for the question. 
Gestalt has a single interface for retrieving primitive objects, classes and interfaces. See the [example ](https://github.com/gestalt-config/gestalt#example) in the documentation for Objects.

For example:
```
 // load a whole class, this works best with pojo's 
  HttpPool pool = gestalt.getConfig("http.pool", HttpPool.class);
  // get a list of objects, or an PlaceHolder collection if there is no hosts found.
  List<Host> hosts = gestalt.getConfig("db.hosts", Collections.emptyList(), new TypeCapture<List<Host>>() {});
```

These are the supported types to [decode](https://github.com/gestalt-config/gestalt#decoders)
I see you are on JDK 13? Records in jdk 14 make a great container for configuration as well, and we support Records. 

For interfaces you can take a look at the examples:
We define an interface at [line 1288](https://github.com/gestalt-config/gestalt/blob/13e54a1b46ae98abd248e72cba0fa9b003313107/gestalt-examples/gestalt-sample/src/test/java/org/github/gestalt/config/integration/GestaltSample.java#L1288C31-L1288C31)
and we retrieve it at [line 921](https://github.com/gestalt-config/gestalt/blob/13e54a1b46ae98abd248e72cba0fa9b003313107/gestalt-examples/gestalt-sample/src/test/java/org/github/gestalt/config/integration/GestaltSample.java#L921C38-L921C38)
The example gets a list of interfaces, but you can get a single interface with 
```
   public interface IHostDefault {
        String getUser();

        String getUrl();

        String getPassword();

        default int getPort() {
            return 10;
        }
    }

    IHostDefault ihostsDefault = gestalt.getConfig("db.hosts", Collections.emptyList(), IHostDefault.class);
```

I am working on cleaning up the documentation. I will try and make it easier to see how to do the basics like decoding an objects and interfaces. I will close this ticket once i have made the documentation more clear.

**Comment by swltr** [comment]
@credmond-git Thank you for the explanation, that sounds promising! I'll have a closer look, but it'll probably take a few days.

And yes, that project is still on Java 13, but I expect that to change with our next major release, which will then most likely update to the latest LTS version.

**Comment by credmond-git** [comment]
Updated the documentation to highlight how to get diffrent java types.

**Comment by swltr** [comment]
@credmond-git After a closer look, it seems that object binding differs from the same way that cfg4j does it - or I am missing something in the documentation. From https://www.cfg4j.org/releases/latest/#introduction:

> 2. Through a binding mechanism. Simply create an interface with methods representing your configuration variables and ask ConfigurationProvider to create a configuration object implementing your interface (i.e. calling `bind("my.configuration.set", MyInterface.class))`. Every time the configuration changes your object will be automatically updated with new values.

The last part is something we make heavy use of: our configurable components get configuration interfaces injected, e.g. [VirtualVehicleConfiguration.java](https://github.com/openTCS/opentcs/blob/66b825b2339f9904146871a3c594805a735dfdc5/openTCS-CommAdapter-Loopback/src/main/java/org/opentcs/virtualvehicle/VirtualVehicleConfiguration.java), and then read configuration values via these configuration interfaces' methods. What's important here is that these methods always provide up-to-date values, which is something that cfg4j does, as long as you configure a reload strategy.

Gestalt also has reload strategies, but if I understand correctly, you have to get a new configuration object via `Gestalt.getConfig()` after a reload to actually get the new value. Is that correct? Or is there a way to have a bound object that always provides up-to-date values?

**Comment by credmond-git** [comment]
When designing Gestalt, it was based on my use cases, which were immutable infrastructure. So even if the proxy object is reloaded it will retain the old values as the proxy caches them and returns the cached values. 

I have a issue to better handle dynamic configurations https://github.com/gestalt-config/gestalt/issues/80

If you wanted to get the latest you would need to get the new proxy object. 
Can you add additional comments in https://github.com/gestalt-config/gestalt/issues/80

**Comment by credmond-git** [comment]
See issue https://github.com/gestalt-config/gestalt/issues/115

**Comment by credmond-git** [comment]
Give release https://github.com/gestalt-config/gestalt/releases/tag/v0.23.2 a try. 
I added a proxy pass-through mode that can be selected using
Gestalt gestalt = builder
            .addSource(abc)
            .addReloadStrategy(reload)
            .setProxyDecoderMode(ProxyDecoderMode.PASSTHROUGH)
            .build();

It should suit your needs.

**Comment by swltr** [comment]
I only get to reply now. That Gestalt is primarily designed for your own use cases is only natural.

Thank you for adding this feature! I'll check out the new version in the next few days and will provide feedback.
