### ISSUE TITLE
Object binding using a constructor.

### ISSUE THREAD

**Issue by LennysLounge** [gestalt-config/gestalt#122]
For https://github.com/opentcs we are still in the process of migrating from cfg4j but we have hit a small roadblock that you could perhaps shed some light on.

With cfg4j we were able to create an object binding from a constructor of that object. This allowed us to encode multiple data in a string and decode that data in the constructor.
```
// config.properties
plantoverviewapp.connectionBookmarks = Localhost|localhost|1099
```
```java
class ConnectionParamSet{
    String description;
    String host;
    int port;

    ConnectionParamSet(String paramString){
        // decode param String into description, host and port.
        ...
    }
}
```
With gestalt, this sort of behaviour doesnt seem possible. Atleast not out of the box. What would be the best way to solve this problem?

Our current solution involves creating a custom `ConnectionParamSetDecoder` to decode a `ConnectionParamSet` specifically. However this solution is undesirable because it involves a specific Object in our gestalt configuration. We would much rather have a generic `StringConstructorDecoder` to decode all types of objects this way.   
A generic decoder however has problems with the priority system as it blocks access to any other type of decoding.

The `DecoderRegistry` currently uses the highest priority decoder only. Perhaps an improvement in this area could be to try all valid decoders in priority order until a decoder successfully decodes the configuration.

Our `StringConstructorDecoder` could then fail and the default `ProxyDecoder` could take over and decode the configuration normaly.

**Comment by credmond-git** [comment]
Thanks for outlining your additional requirements. 
I think i have an idea that should be able to meet your requirements. 
The Decoder class is not that smart about telling if it can decode something. It is only based on if it matches the expected class. 
` boolean matches(TypeCapture<?> klass);`

I am thinking of making this a little smarter so it can also take in the ConfigNode, so it can figure out if given the class type and the data it has (ConfigNode) it can decode it
`boolean canDecode(String path, Tags tags, ConfigNode node, TypeCapture<?> type, DecoderContext decoderContext;`
So it can validate if an Object Decoder has a MapNode, ect. 

Then i can create a StringConstructorDecoder that has something like:
```
`boolean canDecode(String path, Tags tags, ConfigNode node, TypeCapture<?> type, DecoderContext decoderContext;`
f (!(node instanceof LeafNode)) {
return false;
}
Class<?> klass = type.getRawType();
        try {
            Constructor<?> stringConstructor = klass.getConstructor(String.class);
            return return !klass.getRawType().isPrimitive() && !klass.isArray() && !klass.isEnum() &&
            !klass.hasParameter() && !klass.isInterface() && !ignoreTypes.contains(klass.getRawType());
        } catch (NoSuchMethodException e) {
            return false;
        }

public ValidateOf<Object> decode(String path, Tags tags, ConfigNode node, TypeCapture<?> type, DecoderContext decoderContext) {
        if (!(node instanceof LeafNode)) {
     List<TypeCapture<?>> genericInterfaces = type.getParameterTypes();
            return ValidateOf.inValid(new ValidationError.DecodingExpectedMapNodeType(path, genericInterfaces, node));
        }
        Class<?> klass = type.getRawType();

        try {
            Constructor<?> stringConstructor = klass.getConstructor(String.class);
            return return ValidateOf.validateOf(stringConstructor.newInstance(node.getValue().get()));
```

I will take a look at this request next.

**Comment by LennysLounge** [comment]
Yes that would solve our issue nicely.
