### ISSUE TITLE
Extend DurationDecoder to parse Duration

### ISSUE THREAD

**Issue by brainbytes42** [gestalt-config/gestalt#137]
May I suggest to extend the DurationDecoder, so that it is able to decode Durations written in ISO 8601 standardized string format like "PT42S"?

This piece of code ...
https://github.com/gestalt-config/gestalt/blob/84dfdb4195513b48b7b32b6c33fd37ea72ceab55/gestalt-core/src/main/java/org/github/gestalt/config/decoder/DurationDecoder.java#L46-L48
... should therefore have in it's else-block the following:
```
try {
    results = GResultOf.valid(Duration.parse(value));
} catch (Exception e) {
    results = GResultOf.inValid(new ValidationError.ErrorDecodingException(path, node, name()));
}
```

**Comment by credmond-git** [comment]
Thanks that is a great suggestion. I will look into implementing this feature soon.

**Comment by credmond-git** [comment]
Can you please try v0.24.4 and let me know if it resolves your issues

**Comment by brainbytes42** [comment]
Wow, that was a quick fix! :-)
Works perfectly fine, thank you.
