### ISSUE TITLE
Access root node to decode TOML

### ISSUE THREAD

**Issue by brainbytes42** [gestalt-config/gestalt#138]
I have A TOML-File like this
```
[main]
bla = 1

[parts]

[parts.partA]
hello = "World"
foo = "Bar"

[parts.partB]
hello = "Gestalt"
extends = "partA"
```

Now I'd like to parse this file into a hierarchy of java records.

- first problem: I'm unable to access the root node, as an empty path is forbidden and raises a GestaltException. But I'd need to fill my root-record like `record Root(MyMain main, Map<String, MyPart> parts)`... Accessing main and converting that to the MyMain-Record works fine with path "main".

**Comment by credmond-git** [comment]
Hi thanks for the bug report. I have separated this into two issues, for better tracking and resolving. This issue being the accessing a empty root. 

By this do you mean to call something like
HttpPool pool = gestalt.getConfig("", HttpPool.class);
throws an exception?

**Comment by credmond-git** [comment]
Can you please try v0.24.4 and let me know if it resolves your issues

**Comment by brainbytes42** [comment]
Yes, that was what I menat. Works like a charme now, thank you!
