### ISSUE TITLE
Environment Variables Prefix

### ISSUE THREAD

**Issue by brainbytes42** [gestalt-config/gestalt#148]
Hi,

I came across another very useful feature, but first needed to come around som quirks...

[The docs](https://github.com/gestalt-config/gestalt?tab=readme-ov-file#config-sources) suggest a prefix using dot notation, but (running in IntelliJ on Windows) I need to specify the prefix _exactly_ as in my run configuration, ie. with underscore and it appears to be case sensitive. 
Maybe I got something wrong, but I thought to have read, it wouldn't be case sensitive - but I don't find it again...
In any case, a little more docs (maybe javadocs inside the builder?) on this would have been nice... (some parts ar scrambled around, but just having the introductory example, it was tricky... ;-)

Edit: 
Dirty hack for my GestaltBuilder... one for upper, one for lower case... ^^
```
.addSource(EnvironmentConfigSourceBuilder.builder().setPrefix(ENV_VAR_PREFIX_CONTEXT.toUpperCase()).setRemovePrefix(true).build())
.addSource(EnvironmentConfigSourceBuilder.builder().setPrefix(ENV_VAR_PREFIX_CONTEXT.toLowerCase()).setRemovePrefix(true).build())
```

**Comment by credmond-git** [comment]
Thanks for the idea on a nice enhancement. I will add this as a configuration soon.

**Comment by credmond-git** [comment]
Please try v0.24.5. I added a feature to support ignoring case when matching the prefix for env vars. let me know if this works for you.

**Comment by credmond-git** [comment]
As for your second comment, sounds like an interesting problem, but not within the scope of Gestalt. Best of luck figuring it out.

**Comment by brainbytes42** [comment]
> Please try v0.24.5. I added a feature to support ignoring case when matching the prefix for env vars. let me know if this works for you.

Again, works like a charme - thank you!

(And I noticed, the dot-notation is actually working, other than I said originally. I suspect I got confused debugging the case-sensitivity...)

**Comment by brainbytes42** [comment]
Well, sorry... My comment regarding the dot- and snake-notation was incorrect. I just tried it in the prefix, which was silly...

For the node path, an underscore is required, a dot will not be recognized. (separating the prefix is possible with both, dot and underscore.) So I'd recommend changing the example (see link above) in the documentation using dot-notation for the prefix to use underscores as well, as the dot-notation suggests to use it for the path as well. (Or to allow both, dots and underscores...?)

**Comment by credmond-git** [comment]
Gestalt tries to load each source in the standard format of the source. So it expects Environment Variables to be in the Screaming Snake Case. 
I updated the documents here to be more specific here:
https://github.com/gestalt-config/gestalt?tab=readme-ov-file#supported-config-sources

And added this section a few days ago to make things clearer
https://github.com/gestalt-config/gestalt?tab=readme-ov-file#override-using-environment-variables-from-a-environmentconfigsource


Documentation is one of the projects weak points, having one MASSIVE readme is not easily digestible. I have an ongoing ticket to update the docs. 

I am going to close this ticket and Open one to make the Environment Variables delimiter customizable.

**Comment by brainbytes42** [comment]
May I suggest to change [this example](https://github.com/gestalt-config/gestalt?tab=readme-ov-file#config-sources) as well? That was the one getting me onto the wrong track at first... (technically, a prefix with dot-notation isn't wrong - but suggests to use it for the whole path...) ;-)

For the docs, I know this problem from my own experience... :-D maybe split it up using the wiki?
