### ISSUE TITLE
ClassPathConfigSource doesn't support loading files from a standalone JAR

### ISSUE THREAD

**Issue by buildscientist** [gestalt-config/gestalt#62]
Hi @credmond-git - thanks for putting together this great config library. 

I noticed that the `ClassPathConfigSource` doesn't support loading config files when an application is packaged as a standalone JAR with a class based entrypoint (e.g. with a Main method) and all required dependencies (e.g. a fat/uber jar). 

The primary issue stems here from [line 54](https://github.com/gestalt-config/gestalt/blob/main/gestalt-core/src/main/java/org/github/gestalt/config/source/ClassPathConfigSource.java#L54) of `ClassPathConfigSource` where the properties file needs to be located relative to where `ClassPathConfigSource.loadStream()` is being called from.

I believe the correct way to support loading a config file in a standalone JAR is to use `getClass().getClassLoader().getResourceAsStream()` instead.

I have implemented my own class implementing the `ConfigSource` interface that works but will be submitting a PR with a test shortly.

**Comment by credmond-git** [comment]
Thank you for submitting the bug report and I look forward to reviewing your PR.

**Comment by credmond-git** [comment]
When you use the ClassPathConfigSource do you include the backslash in the file name?
ClassPathConfigSource classPathConfigSource = new ClassPathConfigSource("/test.properties")

As described in this blog post
https://www.wissel.net/blog/2021/04/reading-resources-from-jar-files.html

> There are two method returning a resource as an InputStream:

    [Class.getResourceAsStream](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getResourceAsStream-java.lang.String-)
    [ClassLoader.getResourceAsStream](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#getResourceAsStream-java.lang.String-)

> On the surface they do the same, but on a closer look slightly different. Class.getResourceAsStream looks for resources at the path location of the class itself, so when a resource is at the root of the jar, you need a leading /, e.g. /config.json. ClassLoader.getResourceAsStream on the other hand would return null when the resource name is prefixed with /, while without it works as expected e.g. config.json.

I would be open to checking the `getClassLoader().getResourceAsStream()` then if it returns null, as a fallback we can try  `InputStream is = ClassPathConfigSource.class.getResourceAsStream(resource);`. Then if they both return null, we can throw the exception.

**Comment by credmond-git** [comment]
Can you please give Version [0.16.3](https://github.com/gestalt-config/gestalt/releases/tag/v0.16.3) a try. It should make the Classpath loader easier to use as it will try the `getClassLoader().getResourceAsStream() `then `ClassPathConfigSource.class.getResourceAsStream(resource);`

**Comment by buildscientist** [comment]
@credmond-git Has v0.16.3 been pushed to Maven central yet?

**Comment by credmond-git** [comment]
yes they should be available at 
https://repo.maven.apache.org/maven2/com/github/gestalt-config/gestalt-core/0.16.3/

**Comment by buildscientist** [comment]
Confirmed that this resolves the original issue I had. Thanks!
